# Generated by Django 3.0.2 on 2020-02-03 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='leggin',
            name='sizes',
            field=models.ManyToManyField(to='storage.Size'),
        ),
        migrations.AddField(
            model_name='size',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
